[workspace]
resolver = "2"
members = ["noaa_weather_client", "noaa_weather_cli"]

[workspace.dependencies]
anyhow = "1.0.104"
assert_cmd = "2.2.2"
clap = "4.6.6"
comfy-table = "8.0.0"
jiff = "0.2.35"
noaa_weather_client = { path = "noaa_weather_client" }
quick-xml = "0.41.0"
reqwest = "0.13.4"
serde = "1.0.229"
serde_json = "1.0.151"
serde_with = "3.22.0"
tempfile = "3.27.0"
tokio = "1.53.1"
url = "2.5.8"
wiremock = "0.6.5"

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
