[changelog]
body = """

## [{{ version | trim_start_matches(pat="v") }}]{%- if release_link -%}({{ release_link }}){% endif %}
_{{ timestamp | date(format="%d %B %Y") }}_
{% for group, commits in commits | group_by(attribute="group") -%}
{%- if group != "chore" %}
### {{ group | upper_first }}

{% for commit in commits -%}
{%- if commit.scope and commit.scope != package -%}
* *({{commit.scope}})* {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }}{%- if commit.links %} ({% for link in commit.links %}[{{link.text}}]({{link.href}}) {% endfor -%}){% endif %}
{% else -%}
* {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }}
{% endif -%}
{%- endfor %}

{%- endif %}

{%- endfor -%}
"""

commit_parsers = [
    { message = "^feat", group = "added" },
    { message = "^changed", group = "changed" },
    { message = "^deprecated", group = "deprecated" },
    { message = "^fix", group = "fixed" },
    { message = "^security", group = "security" },
    { message = "^chore", group = "chore" },
    { message = "^update", group = "updated dependencies" },
    { message = "^doc", group = "documented" },
    { message = "^.*", group = "other" },
]

[workspace]
release_always = false
features_always_increment_minor = true
dependencies_update = true
release_commits = "^(feat|fix|docs|perf|refactor|revert|test|update)[(:]"

# Disable git releases and tags for all packages by default
git_release_enable = false
git_tag_enable = false

pr_draft = false
pr_labels = ["release"]

[[package]]
name = "noaa_weather_client"
publish = true
# Enable git releases and tags only for the client package
git_release_enable = true
git_tag_enable = true
# Use unified tag naming without package prefix
git_tag_name = "v{{ version }}"
git_release_name = "v{{ version }}"
version_group = "noaa_weather"

[[package]]
name = "noaa_weather_cli"
publish = false
# CLI inherits disabled git releases/tags from workspace
version_group = "noaa_weather"
