[workspace]
release_always = false
dependencies_update = true

pr_draft = true
pr_labels = ["release"]

[[package]]
name = "noaa_weather_client"
publish = true
git_release_enable = true
version_group = "noaa_weather"

[[package]]
name = "noaa_weather_cli"
publish = false
git_release_enable = true
version_group = "noaa_weather"
