[package]
name = "noaa_weather_client"
version = "1.2.0"
edition = "2024"
description = "A client library for the NOAA weather.gov API"
license = "MIT"
repository = "https://github.com/seferino-fernandez/noaa_weather"
keywords = ["weather", "noaa", "nws", "api"]
categories = ["api-bindings"]
homepage = "https://github.com/seferino-fernandez/noaa_weather"
readme = "README.md"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]


[dependencies]
quick-xml = { workspace = true, features = ["serde", "serialize"] }
reqwest = { workspace = true, features = ["json", "multipart", "query"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_with.workspace = true
url.workspace = true

[features]
default = []
radio = []

[dev-dependencies]
wiremock.workspace = true
tokio = { workspace = true, features = ["full"] }
