[package]
name = "noaa_weather_client"
version = "0.1.0"
edition = "2024"
description = "A client library for the NOAA weather.gov API"
license = "MIT"
authors = ["Seferino Fernandez"]
repository = "https://github.com/seferino-fernandez/noaa_weather"

[dependencies]
anyhow = "1.0.97"
reqwest = { version = "0.12.15", features = ["json", "multipart"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_repr = "^0.1.20"
serde_with = { version = "^3.12.0" }
url = "2.5.4"

[dev-dependencies]
wiremock = "0.6.3"
