//! Data models for NOAA Weather API responses.
//!
//! All types implement [`serde::Serialize`] and [`serde::Deserialize`] and
//! map directly to the JSON (or XML) payloads returned by `api.weather.gov`.
//!
//! Types gated behind the **`radio`** feature: [`RadioBroadcast`],
//! [`Paragraph`], [`Sentence`], [`SentenceContent`], [`SayAs`], and
//! [`BroadcastMark`].

pub mod astronomical_data;
pub use self::astronomical_data::AstronomicalData;
pub mod alert;
pub use self::alert::Alert;
pub mod alert_atom_entry;
pub use self::alert_atom_entry::AlertAtomEntry;
pub mod alert_atom_entry_author;
pub use self::alert_atom_entry_author::AlertAtomEntryAuthor;
pub mod alert_atom_feed;
pub use self::alert_atom_feed::AlertAtomFeed;
pub mod alert_atom_feed_author;
pub use self::alert_atom_feed_author::AlertAtomFeedAuthor;
pub mod alert_certainty;
pub use self::alert_certainty::AlertCertainty;
pub mod alert_geocode;
pub use self::alert_geocode::AlertGeocode;
pub mod alert_message_type;
pub use self::alert_message_type::AlertMessageType;
pub mod alert_references_inner;
pub use self::alert_references_inner::AlertReferencesInner;
pub mod alert_severity;
pub use self::alert_severity::AlertSeverity;
pub mod alert_status;
pub use self::alert_status::AlertStatus;
pub mod alert_urgency;
pub use self::alert_urgency::AlertUrgency;
pub mod alert_scope;
pub use self::alert_scope::AlertScope;
pub mod alert_xml_parameter;
pub use self::alert_xml_parameter::AlertXmlParameter;
pub mod active_alerts_count_response;
pub use self::active_alerts_count_response::ActiveAlertsCountResponse;
pub mod alert_types_response;
pub use self::alert_types_response::AlertTypesResponse;
pub mod area_code;
pub use self::area_code::AreaCode;
pub mod center_weather_advisory;
pub use self::center_weather_advisory::CenterWeatherAdvisory;
pub mod cwsu_office;
pub use self::cwsu_office::CwsuOffice;
pub mod gridpoint;
pub use self::gridpoint::Gridpoint;
pub mod gridpoint_12h_forecast;
pub use self::gridpoint_12h_forecast::Gridpoint12hForecast;
pub mod gridpoint_12h_forecast_period;
pub use self::gridpoint_12h_forecast_period::Gridpoint12hForecastPeriod;
pub mod gridpoint_hourly_forecast;
pub use self::gridpoint_hourly_forecast::GridpointHourlyForecast;
pub mod gridpoint_hourly_forecast_period;
pub use self::gridpoint_hourly_forecast_period::GridpointHourlyForecastPeriod;
pub mod gridpoint_forecast_units;
pub use self::gridpoint_forecast_units::GridpointForecastUnits;
pub mod gridpoint_hazards;
pub use self::gridpoint_hazards::GridpointHazards;
pub mod gridpoint_hazards_values_inner;
pub use self::gridpoint_hazards_values_inner::GridpointHazardsValuesInner;
pub mod gridpoint_hazards_values_inner_value_inner;
pub use self::gridpoint_hazards_values_inner_value_inner::GridpointHazardsValuesInnerValueInner;
pub mod gridpoint_quantitative_value_layer;
pub use self::gridpoint_quantitative_value_layer::GridpointQuantitativeValueLayer;
pub mod gridpoint_quantitative_value_layer_values_inner;
pub use self::gridpoint_quantitative_value_layer_values_inner::GridpointQuantitativeValueLayerValuesInner;
pub mod gridpoint_weather;
pub use self::gridpoint_weather::GridpointWeather;
pub mod gridpoint_weather_values_inner;
pub use self::gridpoint_weather_values_inner::GridpointWeatherValuesInner;
pub mod gridpoint_weather_values_inner_value_inner;
pub use self::gridpoint_weather_values_inner_value_inner::GridpointWeatherValuesInnerValueInner;
pub mod glossary;
pub use self::glossary::{GlossaryResponse, GlossaryTerm};
pub mod iso8601_interval;
pub use self::iso8601_interval::Iso8601Interval;
pub mod json_ld_context;
pub use self::json_ld_context::{JsonLdContext, JsonLdContextElement};
pub mod land_region_code;
pub use self::land_region_code::LandRegionCode;
pub mod marine_area_code;
pub use self::marine_area_code::MarineAreaCode;
pub mod marine_region_code;
pub use self::marine_region_code::MarineRegionCode;
pub mod metar_phenomenon;
pub use self::metar_phenomenon::MetarPhenomenon;
pub mod metar_sky_coverage;
pub use self::metar_sky_coverage::MetarSkyCoverage;
pub mod nws_center_weather_service_unit_id;
pub use self::nws_center_weather_service_unit_id::NwsCenterWeatherServiceUnitId;
pub mod nws_forecast_office_id;
pub use self::nws_forecast_office_id::NwsForecastOfficeId;
pub mod nws_national_hqid;
pub use self::nws_national_hqid::NwsNationalHqid;
pub mod nws_office_id;
pub use self::nws_office_id::{NwsOfficeId, ParseNwsOfficeIdError};
pub mod nws_regional_hqid;
pub use self::nws_regional_hqid::NwsRegionalHqid;
pub mod nws_unit_code;
pub use self::nws_unit_code::NwsUnitCode;
pub mod nws_zone_type;
pub use self::nws_zone_type::NwsZoneType;
pub mod noaa_weather_radio;
pub use self::noaa_weather_radio::NoaaWeatherRadio;
pub mod observation;
pub use self::observation::Observation;
pub mod observation_cloud_layers_inner;
pub use self::observation_cloud_layers_inner::ObservationCloudLayersInner;
pub mod observation_station;
pub use self::observation_station::ObservationStation;
pub mod office;
pub use self::office::Office;
pub mod office_address;
pub use self::office_address::OfficeAddress;
pub mod office_headline;
pub use self::office_headline::OfficeHeadline;
pub mod office_headline_collection;
pub use self::office_headline_collection::OfficeHeadlineCollection;
pub mod office_documents;
pub use self::office_documents::{
    NwsConnectDocumentMetadata, OfficeBriefing, OfficeBriefingResponse, OfficeWeatherStory,
    OfficeWeatherStoryCollection,
};
pub mod point;
pub use self::point::Point;
pub mod point_type;
pub use self::point_type::PointType;
pub mod problem_detail;
pub use self::problem_detail::ProblemDetail;
pub mod quality_control;
pub use self::quality_control::QualityControl;
pub mod quantitative_value;
pub use self::quantitative_value::QuantitativeValue;
pub mod radar;
pub use self::radar::{RadarNormalizationError, RadarServerTelemetry, RadarStationTelemetry};
pub mod radar_queue;
pub use self::radar_queue::RadarQueue;
pub mod radar_queue_host;
pub use self::radar_queue_host::RadarQueueHost;
pub mod radar_queues_response;
pub use self::radar_queues_response::RadarQueuesResponse;
pub mod radar_server;
pub use self::radar_server::RadarServer;
pub mod radar_servers_response;
pub use self::radar_servers_response::RadarServersResponse;
pub mod radar_station_alarm;
pub use self::radar_station_alarm::RadarStationAlarm;
pub mod radar_station_alarms_response;
pub use self::radar_station_alarms_response::RadarStationAlarmsResponse;
pub mod radar_station;
pub use self::radar_station::{RadarStation, RadarStationFeature};
pub mod radar_stations_response;
pub use self::radar_stations_response::RadarStationsResponse;
pub mod radar_spgds;
pub use self::radar_spgds::{
    RadarSpgdsDiskStatus, RadarSpgdsEntry, RadarSpgdsGatewayStatus, RadarSpgdsLdmStatus,
    RadarSpgdsResponse, RadarSpgdsStatus, RadarSpgdsThroughput, RadarSpgdsUptime,
};
pub mod region_code;
pub use self::region_code::RegionCode;
pub mod relative_location;
pub use self::relative_location::RelativeLocation;
pub mod sigmet;
pub use self::sigmet::Sigmet;
pub mod state_territory_code;
pub use self::state_territory_code::StateTerritoryCode;
pub mod terminal_aerodrome_forecast;
pub use self::terminal_aerodrome_forecast::TerminalAerodromeForecast;
pub mod terminal_aerodrome_forecasts_response;
pub use self::terminal_aerodrome_forecasts_response::TerminalAerodromeForecastsResponse;
pub mod text_product;
pub use self::text_product::TextProduct;
pub mod text_product_collection;
pub use self::text_product_collection::TextProductCollection;
pub mod text_product_location_collection;
pub use self::text_product_location_collection::TextProductLocationCollection;
pub mod text_product_type_collection;
pub use self::text_product_type_collection::TextProductTypeCollection;
pub mod text_product_type_collection_graph_inner;
pub use self::text_product_type_collection_graph_inner::TextProductTypeCollectionGraphInner;
pub mod unit_code;
pub use self::unit_code::{UnitCodeType, ValueUnit};
pub mod wmo_unit_code;
pub use self::wmo_unit_code::WmoUnitCode;
pub mod zone;
pub use self::zone::Zone;
pub mod zone_forecast;
pub use self::zone_forecast::ZoneForecast;
pub mod zone_forecast_periods_inner;
pub use self::zone_forecast_periods_inner::ZoneForecastPeriodsInner;
pub mod zone_state;
pub use self::zone_state::ZoneState;
pub mod radio_broadcast;
pub use self::radio_broadcast::*;
pub mod radio_transmitter;
pub use self::radio_transmitter::{RadioTransmitter, RadioTransmitterCollection};
