[package]
name = "noaa_weather_cli"
version = "0.1.0"
edition = "2024"
description = "A CLI for the NOAA Weather API client."
license = "MIT"
authors = ["Seferino Fernandez"]
repository = "https://github.com/seferino-fernandez/noaa_weather"

[dependencies]
noaa_weather_client = { path = "../noaa_weather_client" }

clap = { version = "4.5.38", features = ["derive"] }
tokio = { version = "1.45.0", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0.98"
serde_json = "1.0.140"
clap-verbosity-flag = "3.0.2"
comfy-table = "7.1.4"
jiff = "0.2.13"

[dev-dependencies]
assert_cmd = "2.0.17"
tempfile = "3.20.0"
