[package]
name = "noaa_weather_cli"
version = "0.1.0"
edition = "2024"
description = "A CLI for the NOAA Weather API client."
license = "MIT"
authors = ["Seferino Fernandez"]
repository = "https://github.com/seferino-fernandez/noaa_weather"

[dependencies]
noaa_weather_client = { path = "../noaa_weather_client" }

clap = { version = "4.5.35", features = ["derive"] }
config = "0.15.11"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0.97"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
clap-verbosity-flag = "3.0.2"

[dev-dependencies]
assert_cmd = "2.0.16"
